// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrS8bMYoNwJYhbVpXMQfCaXDH8WDQ0QA',
    appId: '1:344072126869:web:e9cf53188e2f94ea3bb69c',
    messagingSenderId: '344072126869',
    projectId: 'saas-cf290',
    authDomain: 'saas-cf290.firebaseapp.com',
    storageBucket: 'saas-cf290.firebasestorage.app',
    measurementId: 'G-2CSSC5LNV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTegmAAsW3vo5GTzs9_FU07hfpMl1VVo',
    appId: '1:344072126869:android:479f4a8db064136c3bb69c',
    messagingSenderId: '344072126869',
    projectId: 'saas-cf290',
    storageBucket: 'saas-cf290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIOVCQbM8-fG_BbyBP-r-DY3Q0DfrVjw',
    appId: '1:344072126869:ios:893a58753a4b996d3bb69c',
    messagingSenderId: '344072126869',
    projectId: 'saas-cf290',
    storageBucket: 'saas-cf290.firebasestorage.app',
    iosBundleId: 'com.saas.saasProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABIOVCQbM8-fG_BbyBP-r-DY3Q0DfrVjw',
    appId: '1:344072126869:ios:893a58753a4b996d3bb69c',
    messagingSenderId: '344072126869',
    projectId: 'saas-cf290',
    storageBucket: 'saas-cf290.firebasestorage.app',
    iosBundleId: 'com.saas.saasProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMrS8bMYoNwJYhbVpXMQfCaXDH8WDQ0QA',
    appId: '1:344072126869:web:0de4c43e70a5e7053bb69c',
    messagingSenderId: '344072126869',
    projectId: 'saas-cf290',
    authDomain: 'saas-cf290.firebaseapp.com',
    storageBucket: 'saas-cf290.firebasestorage.app',
    measurementId: 'G-1WC3DEDEC4',
  );
}
